routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index');

Auth::routes();

// Route::get('/home', 'HomeController@index');

Route::resource('home', 'HomeController');
Route::get('result', 'HomeController@result');
Route::post('home', 'HomeController@proses_estimasi')->name('home.proses_estimasi');
Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'HomeController@selectAjax']);
Route::post('select-ajax_2', ['as'=>'select-ajax_2','uses'=>'HomeController@selectAjax_2']);
Route::post('select-mesin', ['as'=>'select-mesin','uses'=>'HomeController@pilihmesin']);
// Route::post('select-mesin','HomeController@pilihmesin')->name('home.select-mesin');

Route::resource('dashboard', 'DashboardController');

Route::resource('mereks', 'merekController');

Route::resource('modelMereks', 'model_merekController');

Route::resource('tipeModels', 'tipe_modelController');

Route::resource('warnas', 'warnaController');

Route::resource('kondisiMesins', 'kondisi_mesinController');

Route::resource('kondisiSistemRems', 'kondisi_sistem_remController');

Route::resource('kondisiKemudis', 'kondisi_kemudiController');

Route::resource('kondisiSuspensis', 'kondisi_suspensiController');

Route::resource('kondisiEksteriors', 'kondisi_eksteriorController');

Route::resource('kondisiInteriors', 'kondisi_interiorController');

Route::resource('kondisiDokumens', 'kondisi_dokumenController');

Route::resource('mobilBekas', 'mobil_bekasController');

Route::resource('perhitungans', 'perhitunganController');

Route::resource('tipeTransmisis', 'tipe_transmisiController');

Route::resource('laporans', 'laporanController');

app/Models/kondisi_eksterior.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class kondisi_eksterior
 * @package App\Models
 * @version September 26, 2019, 1:21 pm UTC
 *
 * @property string nama_kondisi
 * @property string keterangan
 */
class kondisi_eksterior extends Model
{
    use SoftDeletes;

    public $table = 'kondisi_eksteriors';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nama_kondisi',
        'keterangan'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nama_kondisi' => 'string',
        'keterangan' => 'text'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nama_kondisi' => 'required'
    ];

    
}

app/Http/Controllers/kondisi_eksteriorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createkondisi_eksteriorRequest;
use App\Http\Requests\Updatekondisi_eksteriorRequest;
use App\Repositories\kondisi_eksteriorRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class kondisi_eksteriorController extends AppBaseController
{
    /** @var  kondisi_eksteriorRepository */
    private $kondisiEksteriorRepository;

    public function __construct(kondisi_eksteriorRepository $kondisiEksteriorRepo)
    {
        $this->middleware('auth');
        $this->kondisiEksteriorRepository = $kondisiEksteriorRepo;
    }

    /**
     * Display a listing of the kondisi_eksterior.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $kondisiEksteriors = $this->kondisiEksteriorRepository->paginate(10);

        return view('kondisi_eksteriors.index')
            ->with('kondisiEksteriors', $kondisiEksteriors);
    }

    /**
     * Show the form for creating a new kondisi_eksterior.
     *
     * @return Response
     */
    public function create()
    {
        return view('kondisi_eksteriors.create');
    }

    /**
     * Store a newly created kondisi_eksterior in storage.
     *
     * @param Createkondisi_eksteriorRequest $request
     *
     * @return Response
     */
    public function store(Createkondisi_eksteriorRequest $request)
    {
        $input = $request->all();

        $kondisiEksterior = $this->kondisiEksteriorRepository->create($input);

        Flash::success('Kondisi Eksterior saved successfully.');

        return redirect(route('kondisiEksteriors.index'));
    }

    /**
     * Display the specified kondisi_eksterior.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $kondisiEksterior = $this->kondisiEksteriorRepository->find($id);

        if (empty($kondisiEksterior)) {
            Flash::error('Kondisi Eksterior not found');

            return redirect(route('kondisiEksteriors.index'));
        }

        return view('kondisi_eksteriors.show')->with('kondisiEksterior', $kondisiEksterior);
    }

    /**
     * Show the form for editing the specified kondisi_eksterior.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $kondisiEksterior = $this->kondisiEksteriorRepository->find($id);

        if (empty($kondisiEksterior)) {
            Flash::error('Kondisi Eksterior not found');

            return redirect(route('kondisiEksteriors.index'));
        }

        return view('kondisi_eksteriors.edit')->with('kondisiEksterior', $kondisiEksterior);
    }

    /**
     * Update the specified kondisi_eksterior in storage.
     *
     * @param int $id
     * @param Updatekondisi_eksteriorRequest $request
     *
     * @return Response
     */
    public function update($id, Updatekondisi_eksteriorRequest $request)
    {
        $kondisiEksterior = $this->kondisiEksteriorRepository->find($id);

        if (empty($kondisiEksterior)) {
            Flash::error('Kondisi Eksterior not found');

            return redirect(route('kondisiEksteriors.index'));
        }

        $kondisiEksterior = $this->kondisiEksteriorRepository->update($request->all(), $id);

        Flash::success('Kondisi Eksterior updated successfully.');

        return redirect(route('kondisiEksteriors.index'));
    }

    /**
     * Remove the specified kondisi_eksterior from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $kondisiEksterior = $this->kondisiEksteriorRepository->find($id);

        if (empty($kondisiEksterior)) {
            Flash::error('Kondisi Eksterior not found');

            return redirect(route('kondisiEksteriors.index'));
        }

        $this->kondisiEksteriorRepository->delete($id);

        Flash::success('Kondisi Eksterior deleted successfully.');

        return redirect(route('kondisiEksteriors.index'));
    }
}

resources/views/kondisi_eksteriors/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('kondisiEksteriors.index') !!}">Kondisi Eksterior</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Kondisi Eksterior</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'kondisiEksteriors.store']) !!}

                                   @include('kondisi_eksteriors.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/kondisi_eksteriors/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('kondisiEksteriors.index') !!}">Kondisi Eksterior</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Kondisi Eksterior</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($kondisiEksterior, ['route' => ['kondisiEksteriors.update', $kondisiEksterior->id], 'method' => 'patch']) !!}

                              @include('kondisi_eksteriors.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/kondisi_eksteriors/fields.blade.php
<!-- Nama Kondisi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_kondisi', 'Nama Kondisi:') !!}
    {!! Form::text('nama_kondisi', null, ['class' => 'form-control']) !!}
</div>

<!-- Nilai Field -->
<div class="form-group col-sm-6">
    {!! Form::label('keterangan', 'Keterangan:') !!}
    {!! Form::text('keterangan', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('kondisiEksteriors.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/kondisi_eksteriors/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Kondisi Eksteriors</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             kondisi_eksteriors
                             <a class="pull-right" href="{!! route('kondisiEksteriors.create') !!}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('kondisi_eksteriors.table')
                              <div class="pull-right mr-3">
                                     
        @include('coreui-templates::common.paginate', ['records' => $kondisiEksteriors])

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/kondisi_eksteriors/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{!! route('kondisiEksteriors.index') !!}">Kondisi Eksterior</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{!! route('kondisiEksteriors.index') !!}" class="btn btn-ghost-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('kondisi_eksteriors.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/kondisi_eksteriors/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $kondisiEksterior->id !!}</p>
</div>

<!-- Nama Kondisi Field -->
<div class="form-group">
    {!! Form::label('nama_kondisi', 'Nama Kondisi:') !!}
    <p>{!! $kondisiEksterior->nama_kondisi !!}</p>
</div>

<!-- Nilai Field -->
<div class="form-group">
    {!! Form::label('keterangan', 'Keterangan:') !!}
    <p>{!! $kondisiEksterior->keterangan !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $kondisiEksterior->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $kondisiEksterior->updated_at !!}</p>
</div>

resources/views/kondisi_eksteriors/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="kondisiEksteriors-table">
        <thead>
            <th>Nama Kondisi</th>
        <!-- <th>Nilai</th> -->
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($kondisiEksteriors as $kondisiEksterior)
            <tr>
                <td>{!! $kondisiEksterior->nama_kondisi !!}</td>
            <!-- <td>{!! $kondisiEksterior->nilai !!}</td> -->
                <td>
                    {!! Form::open(['route' => ['kondisiEksteriors.destroy', $kondisiEksterior->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('kondisiEksteriors.show', [$kondisiEksterior->id]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{!! route('kondisiEksteriors.edit', [$kondisiEksterior->id]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>