routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index');

Auth::routes();

// Route::get('/home', 'HomeController@index');

Route::resource('home', 'HomeController');
Route::get('result', 'HomeController@result');
Route::post('home', 'HomeController@proses_estimasi')->name('home.proses_estimasi');
Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'HomeController@selectAjax']);
Route::post('select-ajax_2', ['as'=>'select-ajax_2','uses'=>'HomeController@selectAjax_2']);
Route::post('select-mesin', ['as'=>'select-mesin','uses'=>'HomeController@pilihmesin']);
// Route::post('select-mesin','HomeController@pilihmesin')->name('home.select-mesin');

Route::resource('dashboard', 'DashboardController');

Route::resource('mereks', 'merekController');

Route::resource('modelMereks', 'model_merekController');

Route::resource('tipeModels', 'tipe_modelController');

Route::resource('warnas', 'warnaController');

Route::resource('kondisiMesins', 'kondisi_mesinController');

Route::resource('kondisiSistemRems', 'kondisi_sistem_remController');

Route::resource('kondisiKemudis', 'kondisi_kemudiController');

Route::resource('kondisiSuspensis', 'kondisi_suspensiController');

Route::resource('kondisiEksteriors', 'kondisi_eksteriorController');

Route::resource('kondisiInteriors', 'kondisi_interiorController');

Route::resource('kondisiDokumens', 'kondisi_dokumenController');

Route::resource('mobilBekas', 'mobil_bekasController');

Route::resource('perhitungans', 'perhitunganController');

Route::resource('tipeTransmisis', 'tipe_transmisiController');

Route::resource('laporans', 'laporanController');

app/Models/tipe_model.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\model_merek;

/**
 * Class tipe_model
 * @package App\Models
 * @version September 26, 2019, 12:45 pm UTC
 *
 * @property string nama_tipe_m
 * @property integer id_model_m
 */
class tipe_model extends Model
{
    use SoftDeletes;

    public $table = 'tipe_models';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nama_tipe',
        'model_merek_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nama_tipe' => 'string',
        'model_merek_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nama_tipe' => 'required',
        'model_merek_id' => 'required'
    ];

    public function get_model()
    {
        return $this->belongsTo('App\\Models\\model_merek','model_merek_id','id');
    }
    
    public function get_mobil_bekas()
    {
        return $this->hasMany('App\\Models\\mobil_bekas','tipe_model_id','id');
    }

    public function get_estimasi()
    {
        return $this->hasMany('App\\Models\\Estimasi','tipe_model_id','id');
    }

}

app/Http/Controllers/tipe_modelController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createtipe_modelRequest;
use App\Http\Requests\Updatetipe_modelRequest;
use App\Repositories\tipe_modelRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use App\Models\tipe_model;
use App\Models\model_merek;
use Flash;
use Response;

class tipe_modelController extends AppBaseController
{
    /** @var  tipe_modelRepository */
    private $tipeModelRepository;

    public function __construct(tipe_modelRepository $tipeModelRepo)
    {
        $this->middleware('auth');
        $this->tipeModelRepository = $tipeModelRepo;
    }

    /**
     * Display a listing of the tipe_model.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $tipeModels = tipe_model::with('get_model')->paginate(10);
        // $tipeModels = $this->tipeModelRepository->paginate(10);

        return view('tipe_models.index')
            ->with('tipeModels', $tipeModels);
    }

    /**
     * Show the form for creating a new tipe_model.
     *
     * @return Response
     */
    public function create()
    {   
        // $models = model_merek::pluck('nama_model','id');
        $models = model_merek::all();
        // $models = model_merek::pluck('nama_model','id');
        return view('tipe_models.create', compact('models'));
    }

    /**
     * Store a newly created tipe_model in storage.
     *
     * @param Createtipe_modelRequest $request
     *
     * @return Response
     */
    public function store(Createtipe_modelRequest $request)
    {
        $input = $request->all();

        $tipeModel = $this->tipeModelRepository->create($input);

        Flash::success('Tipe Model saved successfully.');

        return redirect(route('tipeModels.index'));
    }

    /**
     * Display the specified tipe_model.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tipeModel = $this->tipeModelRepository->find($id);

        if (empty($tipeModel)) {
            Flash::error('Tipe Model not found');

            return redirect(route('tipeModels.index'));
        }

        return view('tipe_models.show')->with('tipeModel', $tipeModel);
    }

    /**
     * Show the form for editing the specified tipe_model.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tipeModel = $this->tipeModelRepository->find($id);
        $models = model_merek::all();
        // $models = model_merek::pluck('nama_model','id');

        if (empty($tipeModel)) {
            Flash::error('Tipe Model not found');

            return redirect(route('tipeModels.index'));
        }

        return view('tipe_models.edit', compact('tipeModel','models'));
    }

    /**
     * Update the specified tipe_model in storage.
     *
     * @param int $id
     * @param Updatetipe_modelRequest $request
     *
     * @return Response
     */
    public function update($id, Updatetipe_modelRequest $request)
    {
        $tipeModel = $this->tipeModelRepository->find($id);

        if (empty($tipeModel)) {
            Flash::error('Tipe Model not found');

            return redirect(route('tipeModels.index'));
        }

        $tipeModel = $this->tipeModelRepository->update($request->all(), $id);

        Flash::success('Tipe Model updated successfully.');

        return redirect(route('tipeModels.index'));
    }

    /**
     * Remove the specified tipe_model from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tipeModel = $this->tipeModelRepository->find($id);

        if (empty($tipeModel)) {
            Flash::error('Tipe Model not found');

            return redirect(route('tipeModels.index'));
        }

        $this->tipeModelRepository->delete($id);

        Flash::success('Tipe Model deleted successfully.');

        return redirect(route('tipeModels.index'));
    }
}

resources/views/tipe_models/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('tipeModels.index') !!}">Tipe Model</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Tipe Model</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'tipeModels.store']) !!}

                                   @include('tipe_models.fields_create')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/tipe_models/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('tipeModels.index') !!}">Tipe Model</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Tipe Model</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($tipeModel, ['route' => ['tipeModels.update', $tipeModel->id], 'method' => 'patch']) !!}

                              @include('tipe_models.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/tipe_models/fields.blade.php
<!-- Nama Tipe M Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_tipe', 'Nama Tipe:') !!}
    {!! Form::text('nama_tipe', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Model M Field -->
<div class="form-group col-sm-6">
	<select class="form-control" id="modelSelect">
    @foreach($models as $data)                              
      <option value="{{ $data->id }}" @if($data->id == $tipeModel->model_merek_id) 
        selected='selected' @endif >{{ $data->nama_model }}</option>
    @endforeach
	</select>
	<!-- {!! Form::label('model_merek', 'Model:') !!}
    {!! Form::select('model_merek_id', $models, null, ['class' => 'form-control']) !!} -->
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('tipeModels.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/tipe_models/fields_create.blade.php
<!-- Nama Tipe M Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_tipe', 'Nama Tipe:') !!}
    {!! Form::text('nama_tipe', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Model M Field -->
<div class="form-group col-sm-6">
	<select class="form-control" id="modelSelect" name="model_merek_id">
    @foreach($models as $data)                              
      <option value="{{ $data->id }}">{{ $data->nama_model }}</option>
    @endforeach
	</select>
	<!-- {!! Form::label('model_merek', 'Model:') !!}
    {!! Form::select('model_merek_id', $models, null, ['class' => 'form-control']) !!} -->
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('tipeModels.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/tipe_models/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Tipe Models</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             tipe_models
                             <a class="pull-right" href="{!! route('tipeModels.create') !!}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('tipe_models.table')
                              <div class="pull-right mr-3">
                                     
        @include('coreui-templates::common.paginate', ['records' => $tipeModels])

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/tipe_models/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{!! route('tipeModels.index') !!}">Tipe Model</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{!! route('tipeModels.index') !!}" class="btn btn-ghost-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('tipe_models.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/tipe_models/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $tipeModel->id !!}</p>
</div>

<!-- Nama Tipe M Field -->
<div class="form-group">
    {!! Form::label('nama_tipe', 'Nama Tipe:') !!}
    <p>{!! $tipeModel->nama_tipe !!}</p>
</div>

<!-- Id Model M Field -->
<div class="form-group">
    {!! Form::label('model_merek_id', 'Model:') !!}
    <p>{!! $tipeModel->model_merek_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $tipeModel->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $tipeModel->updated_at !!}</p>
</div>

resources/views/tipe_models/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="tipeModels-table">
        <thead>
            <th>Nama Tipe</th>
        <th>Model</th>
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($tipeModels as $tipeModel)
            <tr>
                <td>{!! $tipeModel->nama_tipe !!}</td>
            <td>{!! $tipeModel->get_model->nama_model !!}</td>
                <td>
                    {!! Form::open(['route' => ['tipeModels.destroy', $tipeModel->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('tipeModels.show', [$tipeModel->id]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{!! route('tipeModels.edit', [$tipeModel->id]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>