routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index');

Auth::routes();

// Route::get('/home', 'HomeController@index');

Route::resource('home', 'HomeController');
Route::get('result', 'HomeController@result');
Route::post('home', 'HomeController@proses_estimasi')->name('home.proses_estimasi');
Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'HomeController@selectAjax']);
Route::post('select-ajax_2', ['as'=>'select-ajax_2','uses'=>'HomeController@selectAjax_2']);
Route::post('select-mesin', ['as'=>'select-mesin','uses'=>'HomeController@pilihmesin']);
// Route::post('select-mesin','HomeController@pilihmesin')->name('home.select-mesin');

Route::resource('dashboard', 'DashboardController');

Route::resource('mereks', 'merekController');

Route::resource('modelMereks', 'model_merekController');

Route::resource('tipeModels', 'tipe_modelController');

Route::resource('warnas', 'warnaController');

Route::resource('kondisiMesins', 'kondisi_mesinController');

Route::resource('kondisiSistemRems', 'kondisi_sistem_remController');

Route::resource('kondisiKemudis', 'kondisi_kemudiController');

Route::resource('kondisiSuspensis', 'kondisi_suspensiController');

Route::resource('kondisiEksteriors', 'kondisi_eksteriorController');

Route::resource('kondisiInteriors', 'kondisi_interiorController');

Route::resource('kondisiDokumens', 'kondisi_dokumenController');

Route::resource('mobilBekas', 'mobil_bekasController');

Route::resource('perhitungans', 'perhitunganController');

Route::resource('tipeTransmisis', 'tipe_transmisiController');

Route::resource('laporans', 'laporanController');

app/Models/kondisi_mesin.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class kondisi_mesin
 * @package App\Models
 * @version September 26, 2019, 1:03 pm UTC
 *
 * @property string nama_kondisi
 * @property string keterangan
 */
class kondisi_mesin extends Model
{
    use SoftDeletes;

    public $table = 'kondisi_mesins';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nama_kondisi',
        'keterangan'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nama_kondisi' => 'string',
        'keterangan' => 'text'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nama_kondisi' => 'required'
    ];

    
}

app/Http/Controllers/kondisi_mesinController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createkondisi_mesinRequest;
use App\Http\Requests\Updatekondisi_mesinRequest;
use App\Repositories\kondisi_mesinRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class kondisi_mesinController extends AppBaseController
{
    /** @var  kondisi_mesinRepository */
    private $kondisiMesinRepository;

    public function __construct(kondisi_mesinRepository $kondisiMesinRepo)
    {
        $this->middleware('auth');
        $this->kondisiMesinRepository = $kondisiMesinRepo;
    }

    /**
     * Display a listing of the kondisi_mesin.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $kondisiMesins = $this->kondisiMesinRepository->paginate(10);

        return view('kondisi_mesins.index')
            ->with('kondisiMesins', $kondisiMesins);
    }

    /**
     * Show the form for creating a new kondisi_mesin.
     *
     * @return Response
     */
    public function create()
    {
        return view('kondisi_mesins.create');
    }

    /**
     * Store a newly created kondisi_mesin in storage.
     *
     * @param Createkondisi_mesinRequest $request
     *
     * @return Response
     */
    public function store(Createkondisi_mesinRequest $request)
    {
        $input = $request->all();

        $kondisiMesin = $this->kondisiMesinRepository->create($input);

        Flash::success('Kondisi Mesin saved successfully.');

        return redirect(route('kondisiMesins.index'));
    }

    /**
     * Display the specified kondisi_mesin.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $kondisiMesin = $this->kondisiMesinRepository->find($id);

        if (empty($kondisiMesin)) {
            Flash::error('Kondisi Mesin not found');

            return redirect(route('kondisiMesins.index'));
        }

        return view('kondisi_mesins.show')->with('kondisiMesin', $kondisiMesin);
    }

    /**
     * Show the form for editing the specified kondisi_mesin.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $kondisiMesin = $this->kondisiMesinRepository->find($id);

        if (empty($kondisiMesin)) {
            Flash::error('Kondisi Mesin not found');

            return redirect(route('kondisiMesins.index'));
        }

        return view('kondisi_mesins.edit')->with('kondisiMesin', $kondisiMesin);
    }

    /**
     * Update the specified kondisi_mesin in storage.
     *
     * @param int $id
     * @param Updatekondisi_mesinRequest $request
     *
     * @return Response
     */
    public function update($id, Updatekondisi_mesinRequest $request)
    {
        $kondisiMesin = $this->kondisiMesinRepository->find($id);

        if (empty($kondisiMesin)) {
            Flash::error('Kondisi Mesin not found');

            return redirect(route('kondisiMesins.index'));
        }

        $kondisiMesin = $this->kondisiMesinRepository->update($request->all(), $id);

        Flash::success('Kondisi Mesin updated successfully.');

        return redirect(route('kondisiMesins.index'));
    }

    /**
     * Remove the specified kondisi_mesin from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $kondisiMesin = $this->kondisiMesinRepository->find($id);

        if (empty($kondisiMesin)) {
            Flash::error('Kondisi Mesin not found');

            return redirect(route('kondisiMesins.index'));
        }

        $this->kondisiMesinRepository->delete($id);

        Flash::success('Kondisi Mesin deleted successfully.');

        return redirect(route('kondisiMesins.index'));
    }
}

resources/views/kondisi_mesins/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('kondisiMesins.index') !!}">Kondisi Mesin</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Kondisi Mesin</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'kondisiMesins.store']) !!}

                                   @include('kondisi_mesins.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/kondisi_mesins/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('kondisiMesins.index') !!}">Kondisi Mesin</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Kondisi Mesin</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($kondisiMesin, ['route' => ['kondisiMesins.update', $kondisiMesin->id], 'method' => 'patch']) !!}

                              @include('kondisi_mesins.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/kondisi_mesins/fields.blade.php
<!-- Nama Kondisi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_kondisi', 'Nama Kondisi:') !!}
    {!! Form::text('nama_kondisi', null, ['class' => 'form-control']) !!}
</div>

<!-- Nilai Field -->
<div class="form-group col-sm-6">
    {!! Form::label('keterangan', 'Keterangan:') !!}
    {!! Form::text('keterangan', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('kondisiMesins.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/kondisi_mesins/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Kondisi Mesins</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             kondisi_mesins
                             <a class="pull-right" href="{!! route('kondisiMesins.create') !!}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('kondisi_mesins.table')
                              <div class="pull-right mr-3">
                                     
        @include('coreui-templates::common.paginate', ['records' => $kondisiMesins])

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/kondisi_mesins/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{!! route('kondisiMesins.index') !!}">Kondisi Mesin</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{!! route('kondisiMesins.index') !!}" class="btn btn-ghost-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('kondisi_mesins.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/kondisi_mesins/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $kondisiMesin->id !!}</p>
</div>

<!-- Nama Kondisi Field -->
<div class="form-group">
    {!! Form::label('nama_kondisi', 'Nama Kondisi:') !!}
    <p>{!! $kondisiMesin->nama_kondisi !!}</p>
</div>

<!-- Nilai Field -->
<div class="form-group">
    {!! Form::label('keterangan', 'Keterangan:') !!}
    <p>{!! $kondisiMesin->keterangan !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $kondisiMesin->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $kondisiMesin->updated_at !!}</p>
</div>

resources/views/kondisi_mesins/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="kondisiMesins-table">
        <thead>
            <th>Nama Kondisi</th>
        <!-- <th>Nilai</th> -->
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($kondisiMesins as $kondisiMesin)
            <tr>
                <td>{!! $kondisiMesin->nama_kondisi !!}</td>
            <!-- <td>{!! $kondisiMesin->nilai !!}</td> -->
                <td>
                    {!! Form::open(['route' => ['kondisiMesins.destroy', $kondisiMesin->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('kondisiMesins.show', [$kondisiMesin->id]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{!! route('kondisiMesins.edit', [$kondisiMesin->id]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>