routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index');

Auth::routes();

// Route::get('/home', 'HomeController@index');

Route::resource('home', 'HomeController');
Route::get('result', 'HomeController@result');
Route::post('home', 'HomeController@proses_estimasi')->name('home.proses_estimasi');
Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'HomeController@selectAjax']);
Route::post('select-ajax_2', ['as'=>'select-ajax_2','uses'=>'HomeController@selectAjax_2']);
Route::post('select-mesin', ['as'=>'select-mesin','uses'=>'HomeController@pilihmesin']);
// Route::post('select-mesin','HomeController@pilihmesin')->name('home.select-mesin');

Route::resource('dashboard', 'DashboardController');

Route::resource('mereks', 'merekController');

Route::resource('modelMereks', 'model_merekController');

Route::resource('tipeModels', 'tipe_modelController');

Route::resource('warnas', 'warnaController');

Route::resource('kondisiMesins', 'kondisi_mesinController');

Route::resource('kondisiSistemRems', 'kondisi_sistem_remController');

Route::resource('kondisiKemudis', 'kondisi_kemudiController');

Route::resource('kondisiSuspensis', 'kondisi_suspensiController');

Route::resource('kondisiEksteriors', 'kondisi_eksteriorController');

Route::resource('kondisiInteriors', 'kondisi_interiorController');

Route::resource('kondisiDokumens', 'kondisi_dokumenController');

Route::resource('mobilBekas', 'mobil_bekasController');

Route::resource('perhitungans', 'perhitunganController');

Route::resource('tipeTransmisis', 'tipe_transmisiController');

Route::resource('laporans', 'laporanController');

app/Models/kondisi_suspensi.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class kondisi_suspensi
 * @package App\Models
 * @version September 26, 2019, 1:20 pm UTC
 *
 * @property string nama_kondisi
 * @property string keterangan
 */
class kondisi_suspensi extends Model
{
    use SoftDeletes;

    public $table = 'kondisi_suspensis';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nama_kondisi',
        'keterangan'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nama_kondisi' => 'string',
        'keterangan' => 'text'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nama_kondisi' => 'required'
    ];

    
}

app/Http/Controllers/kondisi_suspensiController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createkondisi_suspensiRequest;
use App\Http\Requests\Updatekondisi_suspensiRequest;
use App\Repositories\kondisi_suspensiRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class kondisi_suspensiController extends AppBaseController
{
    /** @var  kondisi_suspensiRepository */
    private $kondisiSuspensiRepository;

    public function __construct(kondisi_suspensiRepository $kondisiSuspensiRepo)
    {
        $this->middleware('auth');
        $this->kondisiSuspensiRepository = $kondisiSuspensiRepo;
    }

    /**
     * Display a listing of the kondisi_suspensi.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $kondisiSuspensis = $this->kondisiSuspensiRepository->paginate(10);

        return view('kondisi_suspensis.index')
            ->with('kondisiSuspensis', $kondisiSuspensis);
    }

    /**
     * Show the form for creating a new kondisi_suspensi.
     *
     * @return Response
     */
    public function create()
    {
        return view('kondisi_suspensis.create');
    }

    /**
     * Store a newly created kondisi_suspensi in storage.
     *
     * @param Createkondisi_suspensiRequest $request
     *
     * @return Response
     */
    public function store(Createkondisi_suspensiRequest $request)
    {
        $input = $request->all();

        $kondisiSuspensi = $this->kondisiSuspensiRepository->create($input);

        Flash::success('Kondisi Suspensi saved successfully.');

        return redirect(route('kondisiSuspensis.index'));
    }

    /**
     * Display the specified kondisi_suspensi.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $kondisiSuspensi = $this->kondisiSuspensiRepository->find($id);

        if (empty($kondisiSuspensi)) {
            Flash::error('Kondisi Suspensi not found');

            return redirect(route('kondisiSuspensis.index'));
        }

        return view('kondisi_suspensis.show')->with('kondisiSuspensi', $kondisiSuspensi);
    }

    /**
     * Show the form for editing the specified kondisi_suspensi.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $kondisiSuspensi = $this->kondisiSuspensiRepository->find($id);

        if (empty($kondisiSuspensi)) {
            Flash::error('Kondisi Suspensi not found');

            return redirect(route('kondisiSuspensis.index'));
        }

        return view('kondisi_suspensis.edit')->with('kondisiSuspensi', $kondisiSuspensi);
    }

    /**
     * Update the specified kondisi_suspensi in storage.
     *
     * @param int $id
     * @param Updatekondisi_suspensiRequest $request
     *
     * @return Response
     */
    public function update($id, Updatekondisi_suspensiRequest $request)
    {
        $kondisiSuspensi = $this->kondisiSuspensiRepository->find($id);

        if (empty($kondisiSuspensi)) {
            Flash::error('Kondisi Suspensi not found');

            return redirect(route('kondisiSuspensis.index'));
        }

        $kondisiSuspensi = $this->kondisiSuspensiRepository->update($request->all(), $id);

        Flash::success('Kondisi Suspensi updated successfully.');

        return redirect(route('kondisiSuspensis.index'));
    }

    /**
     * Remove the specified kondisi_suspensi from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $kondisiSuspensi = $this->kondisiSuspensiRepository->find($id);

        if (empty($kondisiSuspensi)) {
            Flash::error('Kondisi Suspensi not found');

            return redirect(route('kondisiSuspensis.index'));
        }

        $this->kondisiSuspensiRepository->delete($id);

        Flash::success('Kondisi Suspensi deleted successfully.');

        return redirect(route('kondisiSuspensis.index'));
    }
}

resources/views/kondisi_suspensis/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('kondisiSuspensis.index') !!}">Kondisi Suspensi</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Kondisi Suspensi</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'kondisiSuspensis.store']) !!}

                                   @include('kondisi_suspensis.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/kondisi_suspensis/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('kondisiSuspensis.index') !!}">Kondisi Suspensi</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Kondisi Suspensi</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($kondisiSuspensi, ['route' => ['kondisiSuspensis.update', $kondisiSuspensi->id], 'method' => 'patch']) !!}

                              @include('kondisi_suspensis.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/kondisi_suspensis/fields.blade.php
<!-- Nama Kondisi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_kondisi', 'Nama Kondisi:') !!}
    {!! Form::text('nama_kondisi', null, ['class' => 'form-control']) !!}
</div>

<!-- Nilai Field -->
<div class="form-group col-sm-6">
    {!! Form::label('keterangan', 'Keterangan:') !!}
    {!! Form::text('keterangan', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('kondisiSuspensis.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/kondisi_suspensis/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Kondisi Suspensis</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             kondisi_suspensis
                             <a class="pull-right" href="{!! route('kondisiSuspensis.create') !!}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('kondisi_suspensis.table')
                              <div class="pull-right mr-3">
                                     
        @include('coreui-templates::common.paginate', ['records' => $kondisiSuspensis])

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/kondisi_suspensis/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{!! route('kondisiSuspensis.index') !!}">Kondisi Suspensi</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{!! route('kondisiSuspensis.index') !!}" class="btn btn-ghost-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('kondisi_suspensis.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/kondisi_suspensis/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $kondisiSuspensi->id !!}</p>
</div>

<!-- Nama Kondisi Field -->
<div class="form-group">
    {!! Form::label('nama_kondisi', 'Nama Kondisi:') !!}
    <p>{!! $kondisiSuspensi->nama_kondisi !!}</p>
</div>

<!-- Nilai Field -->
<div class="form-group">
    {!! Form::label('keterangan', 'Keterangan:') !!}
    <p>{!! $kondisiSuspensi->keterangan !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $kondisiSuspensi->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $kondisiSuspensi->updated_at !!}</p>
</div>

resources/views/kondisi_suspensis/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="kondisiSuspensis-table">
        <thead>
            <th>Nama Kondisi</th>
        <!-- <th>Nilai</th> -->
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($kondisiSuspensis as $kondisiSuspensi)
            <tr>
                <td>{!! $kondisiSuspensi->nama_kondisi !!}</td>
            <!-- <td>{!! $kondisiSuspensi->nilai !!}</td> -->
                <td>
                    {!! Form::open(['route' => ['kondisiSuspensis.destroy', $kondisiSuspensi->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('kondisiSuspensis.show', [$kondisiSuspensi->id]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{!! route('kondisiSuspensis.edit', [$kondisiSuspensi->id]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>